/**
 * Export utilities — JSON, CSV, PNG, PDF.
 * All browser-side, no server requests.
 */
import { saveAs } from 'file-saver';

export function exportJSON(data: unknown[], fileName: string): void {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  saveAs(blob, `${fileName}-export.json`);
}

export function exportCSV(data: Record<string, unknown>[], fileName: string): void {
  if (data.length === 0) return;
  const headers = Object.keys(data[0]);
  const rows = data.map(row =>
    headers.map(h => {
      const v = row[h];
      const s = v === null || v === undefined ? '' : String(v);
      return s.includes(',') || s.includes('"') || s.includes('\n')
        ? `"${s.replace(/"/g, '""')}"`
        : s;
    }).join(','),
  );
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  saveAs(blob, `${fileName}-export.csv`);
}

export async function exportPNG(elementId: string, fileName: string): Promise<void> {
  const { default: html2canvas } = await import('html2canvas');
  const el = document.getElementById(elementId);
  if (!el) return;
  const canvas = await html2canvas(el, { backgroundColor: '#0f1117', scale: 2 });
  canvas.toBlob(blob => {
    if (blob) saveAs(blob, `${fileName}-chart.png`);
  });
}

export async function exportPDF(elementId: string, fileName: string, title: string = 'Analytics Export'): Promise<void> {
  const { default: html2canvas } = await import('html2canvas');
  const { default: jsPDF } = await import('jspdf');
  const el = document.getElementById(elementId);
  if (!el) return;

  const isDark = document.querySelector('.app-shell')?.classList.contains('dark') ?? true;
  const pageBg = isDark ? '#08090e' : '#f4f5f9';
  const textColor = isDark ? '#eef0f6' : '#111827';
  const borderColor = isDark ? '#6366f1' : '#4f46e5';

  // Temporarily style the element for cleaner capture
  const originalPadding = el.style.padding;
  const originalBg = el.style.background;
  el.style.padding = '20px';
  el.style.background = pageBg;

  const canvas = await html2canvas(el, { backgroundColor: pageBg, scale: 2 });
  
  // Restore style
  el.style.padding = originalPadding;
  el.style.background = originalBg;

  const imgData = canvas.toDataURL('image/png');
  
  // A4 Landscape
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();

  // Draw background
  pdf.setFillColor(pageBg);
  pdf.rect(0, 0, pdfWidth, pdfHeight, 'F');

  // Draw border
  pdf.setDrawColor(borderColor);
  pdf.setLineWidth(3);
  pdf.rect(20, 20, pdfWidth - 40, pdfHeight - 40, 'S');

  // Add Title
  pdf.setTextColor(textColor);
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, 40, 55);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(isDark ? '#9196ab' : '#6b7280');
  pdf.text(`Generated by Excel Analytics • ${new Date().toLocaleDateString()}`, 40, 72);

  // Calculate image dimensions to fit within the border
  const margin = 40;
  const topMargin = 90;
  const maxWidth = pdfWidth - (margin * 2);
  const maxHeight = pdfHeight - topMargin - margin;

  const imgRatio = canvas.width / canvas.height;
  const maxRatio = maxWidth / maxHeight;

  let finalWidth = maxWidth;
  let finalHeight = maxHeight;

  if (imgRatio > maxRatio) {
    finalHeight = maxWidth / imgRatio;
  } else {
    finalWidth = maxHeight * imgRatio;
  }

  const xOffset = margin + (maxWidth - finalWidth) / 2;

  pdf.addImage(imgData, 'PNG', xOffset, topMargin, finalWidth, finalHeight);
  pdf.save(`${fileName}.pdf`);
}
